### ISSUE TITLE
Fixes and improve more for aggregation

### ISSUE THREAD

**Issue by yl-lisen** [timeplus-io/proton#614]
needs to be back ported from community:

~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/61257 (Fix possible incorrect result of aggregate function uniqExact #61257)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/61171 (Remove a few templates from Aggregator.cpp #61171)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/47399 (Remove distinct on top of MergingAggregatedStep #47399)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/44541 (Followup #43761 #44541)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/43761 (Refactor FunctionNode #43761)~~
- [x] https://github.com/ClickHouse/ClickHouse/pull/58542 (Revert "Merging #53757" #58542)
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/50531 (JIT infrastructure refactoring #50531)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/43813 (Better handling of NULL in aggregate combinators, fix possible segfault/logical error #43813)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/45067 (JIT compilation float to bool conversion fix #45067)~~
- [x] https://github.com/ClickHouse/ClickHouse/pull/59009 (uniqExact state parallel merging for distributed queries #59009)
- [x] https://github.com/ClickHouse/ClickHouse/pull/58745 (Fix double destroy call on exception throw in addBatchLookupTable8 #58745)
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/57872 (Better optimization of consecutive keys in aggregation #57872)~~
- [x] https://github.com/ClickHouse/ClickHouse/pull/43945 (Improve hash table preallocation optimisation)
- [x] https://github.com/ClickHouse/ClickHouse/pull/58440 (Enable JIT compilation for aggregation without key)
- [x] https://github.com/ClickHouse/ClickHouse/pull/57258 (Remove addBatchSinglePlaceFromInterval #57258)
- [x] https://github.com/ClickHouse/ClickHouse/pull/56120 (WindowTransform decrease amount of virtual function calls #56120)
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/57074 (Avoid excessive allocation in Arena #57074)~~
- [x] https://github.com/ClickHouse/ClickHouse/pull/53589 (Experiment Aggregator merge and destroy states in batch #53589)
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/53549 (Optimize group by constant keys #53549)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/48607 (Add settings for real-time updates during query execution #48607)~~
- [x] https://github.com/ClickHouse/ClickHouse/pull/51566 (Fix memory consumption when max_block_size is huge in Aggregator + more memory checks #51566)
- [x] https://github.com/ClickHouse/ClickHouse/pull/50748 (Convert hashSets in parallel before merge)
- [x] https://github.com/ClickHouse/ClickHouse/pull/52439 (Fix possible double-free in Aggregator #52439)
- [x] https://github.com/ClickHouse/ClickHouse/pull/50291 (JIT aggregation nullable key fix #50291)
- [x] https://github.com/ClickHouse/ClickHouse/pull/49282 (Fix all key value is null and group use rollup return wrong answer #49282)
- [x] https://github.com/ClickHouse/ClickHouse/pull/45772 (Optimize one nullable key aggregate performance #45772)
- [x] https://github.com/ClickHouse/ClickHouse/pull/45375 (Window view functional test failed on platform s390x)
- [x] https://github.com/ClickHouse/ClickHouse/pull/40762 (Fix GROUPING function SQL compatibility #40762)
- [x] https://github.com/ClickHouse/ClickHouse/pull/39304 (Prefetching in aggregation #39304)
- [x] https://github.com/ClickHouse/ClickHouse/pull/39138 (Control block size in aggregator #39138)
- [x] https://github.com/ClickHouse/ClickHouse/pull/38295 (Quick fix for aggregation pipeline #38295)
- [x] https://github.com/ClickHouse/ClickHouse/pull/39908 (Improve 02354_distributed_with_external_aggregation_memory_usage #39908)
- [x] https://github.com/ClickHouse/ClickHouse/pull/39429 (Improve memory usage during memory efficient merging of aggregation results)
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/37959 (Preserve filling step plan position on sorting optimization #37959)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/39123 (Pushdown filter to the right side of sorting join #39123)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/37393 (Move updateInputStream to ITransformingStep #37393)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/34632 (Optimized processing of ORDER BY in window functions #34632)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/35623 (Functions calculation after sorting #35623)~~
~~- [ ] https://github.com/ClickHouse/ClickHouse/pull/34469 (Added JIT compilation of SortDescription #34469)~~
- [x] https://github.com/ClickHouse/ClickHouse/pull/37163 (Add GROUPING function #37163)
- [x] https://github.com/ClickHouse/ClickHouse/pull/37469 (Implement in order aggregation (optimize_aggregation_in_order) for projections for tables with fully materialized projections #37469)
- [x] https://github.com/ClickHouse/ClickHouse/pull/34305 (Fix various issues when projection is enabled by default #34305)
- [x] https://github.com/ClickHouse/ClickHouse/pull/37093 (Fix GROUP BY AggregateFunction #37093)

**Comment by yokofly** [comment]
add this one. https://github.com/ClickHouse/ClickHouse/pull/37020/files
I have seen we remove this useless code.
https://github.com/timeplus-io/proton/pull/615/commits/dc892977ac278c6286b75363846c86d607cfa3e0#diff-d6da13621eeabbd2e70bb09de71117a1168b2879f03a5fa05340989831a970ffL371
